### ISSUE TITLE
State mutation

### ISSUE THREAD

**Issue by Default4152** [JeremyDownes/Jammming#1]
Important for errors - In React we don't want to mutate the state directly. If we want to update the state, we should be using `this.setState`. In AppPlaylist.js you have the `addTrack` method which sets `let newTracks = this.state.newPlaylist;` - any changes to `newTracks` like the `.push` being made will change `this.state.newPlaylist` behind the scenes as well. You can observe this by putting `console.log(this.state);` on line 14. You can read more about this on the official react documentation here: https://reactjs.org/docs/react-component.html#state

By avoiding updating the state directly, we can maintain more predictability about our applications state.

**Comment by JeremyDownes** [comment]
I'm disappointed with myself for this one. I know better. Even if I didn't refactor I should never have written this.state. = anything. shame
