### ISSUE TITLE
Style guide

### ISSUE THREAD

**Issue by Default4152** [JeremyDownes/Jammming#2]
Simplify - I recommend using a style guide to format your code in a way that improves the readability and organization.

We can make improvements to the indentation, semicolon usage and spacing by following a javascript (React) style guide like this one from airbnb: https://github.com/airbnb/javascript/tree/master/react

**Comment by JeremyDownes** [comment]
Yeah sorry about that. I didn't refactor my first attempt at all you must have looked at that one. I thought it shows dissection (albeit amateur) of the static sight a little better. Thanks for the link though. It lists a lot of guidelines that I wasn't aware of.
