### ISSUE TITLE
Unused files

### ISSUE THREAD

**Issue by Default4152** [JeremyDownes/Jammming#3]
Simplify - (BACKUP) Remove unused files in an effort to bring more organization into the project. If you want to remove files, you can create a git commit with the removal and search for it later using `git log`. I would read this awesome article that goes over git log in more detail here: https://mijingo.com/blog/understanding-git-log

**Comment by JeremyDownes** [comment]
I think you may be mistaking the second version of the project for unused files, My fault probably should have branched but they were built completely independent of each other and a couple weeks apart and a dead project so I just stuck them in the same folder and committed. <small>(it was in my README)</small>
